name: .NET Core

on:
  push:
    branches: [ sharp ]
  pull_request:
    branches: [ sharp ]

jobs:
  build:
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        configuration: [Release, Debug]
        include:
          - os: ubuntu
            platformIdentifier: linux-x64
          - os: macos
            platformIdentifier: osx-x64
          - os: windows
            platformIdentifier: win-x64
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore GmodUltralight/GmodUltralight.sln
    - name: Build
      run: dotnet publish GmodUltralight/GmodUltralight.sln --configuration ${{matrix.configuration}} --framework net5.0
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: GmodUltralight ${{matrix.os}} ${{matrix.configuration}}
        path: "GmodUltralight/bin/${{matrix.configuration}}/net5.0/${{matrix.platformIdentifier}}/publish/*"
  test:
    runs-on: ubuntu-latest
    #needs: build
    steps:
    - run: |
       wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
       tar -xvzf steamcmd_linux.tar.gz
       rm -rfv steamcmd_linux.tar.gz
       ./steamcmd.sh +login anonymous +force_install_dir gmod "+app_update 4020 -beta x86-64 validate" +quit
    - run: sudo apt-get install tree
    - run: tree
    - run: dotnet publish GmodUltralight/GmodUltralight.sln --configuration Debug --framework net5.0 -o ./gmod/garrysmod/lua/bin/Modules/GmodUltralight
    - run: cp GmodUltralight/test.lua gmod/garrysmod/lua/autorun/server
    - name: Run Garry's Mod
      run: ./srcds_run_x64 -game garrysmod -systemtest +sv_hibernate_think 1 || true
      working-directory: ./gmod/
      timeout-minutes: 5