name: .NET Core

on:
  push:
    branches: [ sharp ]
  pull_request:
    branches: [ sharp ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true    # UltralightSharp
        lfs: true           # UltralightSharp large files
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore GmodUltralight/GmodUltralight.sln
    - name: Build
      run: dotnet build GmodUltralight/GmodUltralight.sln --configuration Release --framework net5.0
    - name: Test
      run: dotnet test GmodUltralight/GmodUltralight.sln --no-restore --verbosity normal
