name: .NET Core

on:
  push:
    branches: [ sharp ]
  pull_request:
    branches: [ sharp ]

jobs:
  build:

    runs-on: ${{matrix.os}}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        configuration: [Release, Debug]
        include:
          - os: ubuntu
            platformIdentifier: linux-x64
          - os: macos
            platformIdentifier: osx-x64
          - os: windows
            platformIdentifier: win-x64
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true    # UltralightSharp
        lfs: true           # UltralightSharp large files
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore GmodUltralight/GmodUltralight.sln
    - name: Build
      run: dotnet publish GmodUltralight/GmodUltralight.sln --configuration ${{matrix.configuration}} --framework net5.0
    - run: tree
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: published build
        path: "GmodUltralight/bin/x64/${{matrix.configuration}}/net5.0/${{matrix.platformIdentifier}}/publish/*"
