name: .NET Core

on:
  push:
    branches: [ sharp ]
  pull_request:
    branches: [ sharp ]

jobs:
  build:
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        configuration: [Release, Debug]
        include:
          - os: ubuntu
            platformIdentifier: linux-x64
          - os: macos
            platformIdentifier: osx-x64
          - os: windows
            platformIdentifier: win-x64
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore GmodUltralight.sln
    - name: Build
      run: dotnet publish GmodUltralight.sln --configuration ${{matrix.configuration}} --framework net5.0
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: GmodUltralight ${{matrix.os}} ${{matrix.configuration}}
        path: "GmodUltralight/bin/${{matrix.configuration}}/net5.0/${{matrix.platformIdentifier}}/publish/*"
        retention-days: 10
